// Code generated by MockGen. DO NOT EDIT.
// Source: joblessness/haha/user/interfaces (interfaces: UserRepository)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "joblessness/haha/models"
	reflect "reflect"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ChangeOrganization mocks base method
func (m *MockUserRepository) ChangeOrganization(arg0 models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeOrganization", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeOrganization indicates an expected call of ChangeOrganization
func (mr *MockUserRepositoryMockRecorder) ChangeOrganization(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeOrganization", reflect.TypeOf((*MockUserRepository)(nil).ChangeOrganization), arg0)
}

// ChangePerson mocks base method
func (m *MockUserRepository) ChangePerson(arg0 models.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePerson", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePerson indicates an expected call of ChangePerson
func (mr *MockUserRepositoryMockRecorder) ChangePerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePerson", reflect.TypeOf((*MockUserRepository)(nil).ChangePerson), arg0)
}

// GetListOfOrgs mocks base method
func (m *MockUserRepository) GetListOfOrgs(arg0 int) ([]models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfOrgs", arg0)
	ret0, _ := ret[0].([]models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListOfOrgs indicates an expected call of GetListOfOrgs
func (mr *MockUserRepositoryMockRecorder) GetListOfOrgs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfOrgs", reflect.TypeOf((*MockUserRepository)(nil).GetListOfOrgs), arg0)
}

// GetOrganization mocks base method
func (m *MockUserRepository) GetOrganization(arg0 uint64) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", arg0)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization
func (mr *MockUserRepositoryMockRecorder) GetOrganization(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockUserRepository)(nil).GetOrganization), arg0)
}

// GetPerson mocks base method
func (m *MockUserRepository) GetPerson(arg0 uint64) (*models.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", arg0)
	ret0, _ := ret[0].(*models.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson
func (mr *MockUserRepositoryMockRecorder) GetPerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockUserRepository)(nil).GetPerson), arg0)
}

// GetUserFavorite mocks base method
func (m *MockUserRepository) GetUserFavorite(arg0 uint64) (models.Favorites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavorite", arg0)
	ret0, _ := ret[0].(models.Favorites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavorite indicates an expected call of GetUserFavorite
func (mr *MockUserRepositoryMockRecorder) GetUserFavorite(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavorite", reflect.TypeOf((*MockUserRepository)(nil).GetUserFavorite), arg0)
}

// LikeExists mocks base method
func (m *MockUserRepository) LikeExists(arg0, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeExists indicates an expected call of LikeExists
func (mr *MockUserRepositoryMockRecorder) LikeExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeExists", reflect.TypeOf((*MockUserRepository)(nil).LikeExists), arg0, arg1)
}

// SaveAvatarLink mocks base method
func (m *MockUserRepository) SaveAvatarLink(arg0 string, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAvatarLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAvatarLink indicates an expected call of SaveAvatarLink
func (mr *MockUserRepositoryMockRecorder) SaveAvatarLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAvatarLink", reflect.TypeOf((*MockUserRepository)(nil).SaveAvatarLink), arg0, arg1)
}

// SetOrDeleteLike mocks base method
func (m *MockUserRepository) SetOrDeleteLike(arg0, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrDeleteLike", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetOrDeleteLike indicates an expected call of SetOrDeleteLike
func (mr *MockUserRepositoryMockRecorder) SetOrDeleteLike(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrDeleteLike", reflect.TypeOf((*MockUserRepository)(nil).SetOrDeleteLike), arg0, arg1)
}
