version: '3'
services:
  app:
    image: golang
    env_file:
      - ../env.list
    volumes:
      - .:/go/src/haha
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/haha/cmd/haha/
    ports:
      - "8001:8001"
    command: go run main.go
    stdin_open: true
    tty: true
    network_mode: host

  search:
    image: golang
    env_file:
      - ../env.list
    volumes:
      - .:/go/src/haha
    working_dir: /go/src/haha/cmd/search/
    ports:
      - "8002:8002"
    command: go run main.go
    depends_on:
      - app
    stdin_open: true
    tty: true
    network_mode: host

  interview:
    image: golang
    env_file:
      - ../env.list
    volumes:
      - .:/go/src/haha
    working_dir: /go/src/haha/cmd/interview/
    ports:
      - "8003:8003"
    command: go run main.go
    depends_on:
      - app
    stdin_open: true
    tty: true
    network_mode: host

  auth:
    image: golang
    env_file:
      - ../env.list
    volumes:
      - .:/go/src/haha
    working_dir: /go/src/haha/cmd/auth/
    ports:
      - "8004:8004"
    command: go run main.go
    depends_on:
      - app
    stdin_open: true
    tty: true
    network_mode: host

  prometheus:
    image: prom/prometheus
    volumes:
      - ./haha/prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always