// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package baseModels

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC803d3e7DecodeJoblessnessHahaModelsBase(in *jlexer.Lexer, out *ResponseID) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC803d3e7EncodeJoblessnessHahaModelsBase(out *jwriter.Writer, in ResponseID) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseID) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC803d3e7EncodeJoblessnessHahaModelsBase(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseID) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC803d3e7EncodeJoblessnessHahaModelsBase(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseID) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC803d3e7DecodeJoblessnessHahaModelsBase(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseID) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC803d3e7DecodeJoblessnessHahaModelsBase(l, v)
}
func easyjsonC803d3e7DecodeJoblessnessHahaModelsBase1(in *jlexer.Lexer, out *ResponseBool) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "like":
			out.Like = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC803d3e7EncodeJoblessnessHahaModelsBase1(out *jwriter.Writer, in ResponseBool) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"like\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Like))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseBool) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC803d3e7EncodeJoblessnessHahaModelsBase1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseBool) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC803d3e7EncodeJoblessnessHahaModelsBase1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseBool) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC803d3e7DecodeJoblessnessHahaModelsBase1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseBool) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC803d3e7DecodeJoblessnessHahaModelsBase1(l, v)
}
