// Code generated by MockGen. DO NOT EDIT.
// Source: joblessness/haha/auth (interfaces: UseCase)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "joblessness/haha/models"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// ChangeOrganization mocks base method
func (m *MockUseCase) ChangeOrganization(arg0 models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeOrganization", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeOrganization indicates an expected call of ChangeOrganization
func (mr *MockUseCaseMockRecorder) ChangeOrganization(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeOrganization", reflect.TypeOf((*MockUseCase)(nil).ChangeOrganization), arg0)
}

// ChangePerson mocks base method
func (m *MockUseCase) ChangePerson(arg0 models.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePerson", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePerson indicates an expected call of ChangePerson
func (mr *MockUseCaseMockRecorder) ChangePerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePerson", reflect.TypeOf((*MockUseCase)(nil).ChangePerson), arg0)
}

// GetListOfOrgs mocks base method
func (m *MockUseCase) GetListOfOrgs(arg0 int) ([]models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfOrgs", arg0)
	ret0, _ := ret[0].([]models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListOfOrgs indicates an expected call of GetListOfOrgs
func (mr *MockUseCaseMockRecorder) GetListOfOrgs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfOrgs", reflect.TypeOf((*MockUseCase)(nil).GetListOfOrgs), arg0)
}

// GetOrganization mocks base method
func (m *MockUseCase) GetOrganization(arg0 uint64) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", arg0)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization
func (mr *MockUseCaseMockRecorder) GetOrganization(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockUseCase)(nil).GetOrganization), arg0)
}

// GetPerson mocks base method
func (m *MockUseCase) GetPerson(arg0 uint64) (*models.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", arg0)
	ret0, _ := ret[0].(*models.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson
func (mr *MockUseCaseMockRecorder) GetPerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockUseCase)(nil).GetPerson), arg0)
}

// Login mocks base method
func (m *MockUseCase) Login(arg0, arg1 string) (uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login
func (mr *MockUseCaseMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUseCase)(nil).Login), arg0, arg1)
}

// Logout mocks base method
func (m *MockUseCase) Logout(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout
func (mr *MockUseCaseMockRecorder) Logout(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockUseCase)(nil).Logout), arg0)
}

// RegisterOrganization mocks base method
func (m *MockUseCase) RegisterOrganization(arg0 *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrganization", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterOrganization indicates an expected call of RegisterOrganization
func (mr *MockUseCaseMockRecorder) RegisterOrganization(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrganization", reflect.TypeOf((*MockUseCase)(nil).RegisterOrganization), arg0)
}

// RegisterPerson mocks base method
func (m *MockUseCase) RegisterPerson(arg0 *models.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPerson", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPerson indicates an expected call of RegisterPerson
func (mr *MockUseCaseMockRecorder) RegisterPerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPerson", reflect.TypeOf((*MockUseCase)(nil).RegisterPerson), arg0)
}

// SessionExists mocks base method
func (m *MockUseCase) SessionExists(arg0 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionExists", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionExists indicates an expected call of SessionExists
func (mr *MockUseCaseMockRecorder) SessionExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionExists", reflect.TypeOf((*MockUseCase)(nil).SessionExists), arg0)
}
