// Code generated by MockGen. DO NOT EDIT.
// Source: joblessness/haha/recommendation/interfaces (interfaces: UseCase)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	baseModels "joblessness/haha/models/base"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetRecommendedVacancies mocks base method
func (m *MockUseCase) GetRecommendedVacancies(arg0 uint64) ([]baseModels.Vacancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendedVacancies", arg0)
	ret0, _ := ret[0].([]baseModels.Vacancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendedVacancies indicates an expected call of GetRecommendedVacancies
func (mr *MockUseCaseMockRecorder) GetRecommendedVacancies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendedVacancies", reflect.TypeOf((*MockUseCase)(nil).GetRecommendedVacancies), arg0)
}
