global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['hahao.ru']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['hahao.ru:9100']
