name: Docker build

on:
  push:
    branches: [ microservice ]
  pull_request:
    branches: [ microservice ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8} -f search.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8} -f interview.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8} -f auth.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8} -f app.Dockerfile .

      - name: Push the images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker images
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8}

      - name: Run project
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)
            docker run -d -net=host ${{ secrets.DOCKERHUB_USERNAME }}/search:${GITHUB_SHA::8}
            docker run -d -net=host ${{ secrets.DOCKERHUB_USERNAME }}/interview:${GITHUB_SHA::8}
            docker run -d -net=host ${{ secrets.DOCKERHUB_USERNAME }}/auth:${GITHUB_SHA::8}
            docker run -d -net=host --env-file=/home/env.list -v /etc/letsencrypt:/etc/letsencrypt ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8}